name: frrsa
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - joblib=1.2.*
  - numba=0.56.*
  - numpy=1.23.*
  - pandas=1.5.*
  - psutil=5.9.*
  - python=3.8.*
  - scikit-learn=1.1.*
  - scipy=1.9.*
